export const JOB_ROLES = [
  "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer", "Mobile App Developer", 
  "Data Engineer", "Data Analyst", "Data Scientist", "ML Engineer", "AI Engineer", "DevOps Engineer", 
  "Cloud Engineer", "Site Reliability Engineer", "Cybersecurity Analyst", "Penetration Tester", 
  "Network Engineer", "Database Administrator", "Embedded Systems Engineer", "IoT Engineer", 
  "Blockchain Developer", "QA/Test Engineer", "Systems Architect", "ERP Consultant", "IT Support Engineer", 
  "BI Developer", "Game Developer", "AR/VR Developer", "Design Engineer", "Manufacturing Engineer", 
  "Automotive Engineer", "Aerospace Engineer", "Robotics Engineer", "HVAC Engineer", "Thermal Engineer", 
  "Quality Control Engineer", "Maintenance Engineer", "Piping Engineer", "Tool & Die Engineer", 
  "Product Development Engineer", "Simulation Engineer", "Marine Engineer", "Welding Engineer", 
  "Structural Engineer", "Geotechnical Engineer", "Transportation Engineer", "Environmental Engineer", 
  "Construction Manager", "Quantity Surveyor", "Urban Planner", "Water Resource Engineer", "Surveyor", 
  "Highway Engineer", "Site Engineer", "Bridge Engineer", "Tunnel Engineer", "Electrical Design Engineer", 
  "Power Systems Engineer", "Control Systems Engineer", "Instrumentation Engineer", "Protection Engineer", 
  "Switchgear Engineer", "Telecommunications Engineer", "Signal Processing Engineer", "Substation Engineer", 
  "Solar/Renewable Energy Eng.", "EV/Battery Engineer", "Process Engineer", "Petrochemical Engineer", 
  "Polymer Engineer", "Biochemical Engineer", "Food Technology Engineer", "Materials Engineer", 
  "Safety/HSE Engineer", "Catalyst Engineer", "Formulation Chemist", "VLSI Design Engineer", 
  "PCB Design Engineer", "RF Engineer", "Embedded Software Engineer", "Telecom Engineer", 
  "Hardware Engineer", "Antenna Engineer", "Propulsion Engineer", "Avionics Engineer", "Structural Analyst", 
  "Flight Test Engineer", "Systems Integration Engineer", "Satellite Engineer", "Defense Systems Engineer", 
  "Medical Device Engineer", "Clinical Engineer", "Regulatory Affairs Specialist", "Biomechanics Engineer", 
  "Bioinformatics Analyst", "Industrial Engineer", "Production Engineer", "Lean/Six Sigma Engineer", 
  "Supply Chain Engineer", "Operations Research Analyst", "Plant Manager", "Logistics Engineer", 
  "Business Analyst", "Management Consultant", "Strategy Analyst", "Business Development Manager", 
  "Corporate Planner", "General Manager", "CEO", "COO", "Marketing Manager", "Brand Manager", 
  "Digital Marketing Analyst", "Social Media Manager", "Content Strategist", "Market Research Analyst", 
  "Product Marketing Manager", "Sales Executive", "Key Account Manager", "Regional Sales Manager", 
  "Pre-Sales Consultant", "CRM Analyst", "Growth Hacker", "E-commerce Manager", "Financial Analyst", 
  "Investment Banker", "Credit Analyst", "Risk Manager", "Chartered Accountant (CA/CPA)", "Portfolio Manager", 
  "Equity Research Analyst", "Treasury Analyst", "Tax Consultant", "Actuary", "Compliance Officer", 
  "CFO", "HR Generalist", "Talent Acquisition Specialist", "HR Business Partner", "L&D Manager", 
  "Compensation & Benefits Analyst", "Employee Relations Manager", "HR Analyst", "OD Consultant", 
  "CHRO", "Supply Chain Manager", "Procurement Manager", "Logistics Manager", "Inventory Analyst", 
  "Demand Planner", "Warehouse Manager", "Sourcing Specialist", "Import/Export Manager", "IT Manager", 
  "CTO", "CIO", "Technology Consultant", "IT Project Manager", "Scrum Master", "Product Manager", 
  "Product Owner", "Solution Architect", "SAP/Oracle Consultant", "Hospital Administrator", 
  "Health Informatics Manager", "Clinical Operations Manager", "Public Health Manager", 
  "Medical Coding Analyst", "Pharmaceutical Manager", "Real Estate Manager", "Property Developer", 
  "Facility Manager", "Construction Project Manager", "Valuation Analyst", "UX Designer", "UI Designer", 
  "Product Designer", "Industrial Designer", "Graphic Designer", "Motion Designer", "Interior Designer", 
  "Architect", "Engineering Manager", "R&D Manager", "QA Manager", "Operations Manager", 
  "Compliance Manager", "ESG/Sustainability Manager", "Change Management Specialist"
];
