import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Header from '@/components/Header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { BrainCircuit, Code, Cpu, Wrench, GraduationCap, Clock, HelpCircle, AlertCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';

const TEST_TYPES = [
  {
    id: 'aptitude',
    title: 'Aptitude Mastery',
    description: 'Quantitative, Logical Reasoning, Verbal',
    icon: BrainCircuit,
    time: 30,
    questions: 30,
    difficulty: 'Medium',
    color: 'from-blue-500/20 to-cyan-500/20',
    iconColor: 'text-cyan-400'
  },
  {
    id: 'tech-cse',
    title: 'Technical Core — CSE',
    description: 'OOPs, DBMS, OS, CN, DSA',
    icon: Code,
    time: 45,
    questions: 40,
    difficulty: 'Hard',
    color: 'from-emerald-500/20 to-green-500/20',
    iconColor: 'text-emerald-400'
  },
  {
    id: 'tech-ece',
    title: 'Technical Core — ECE',
    description: 'Analog, Digital, Signals & Systems',
    icon: Cpu,
    time: 45,
    questions: 40,
    difficulty: 'Hard',
    color: 'from-orange-500/20 to-amber-500/20',
    iconColor: 'text-orange-400'
  },
  {
    id: 'tech-me',
    title: 'Technical Core — ME',
    description: 'Thermodynamics, Fluid Mechanics, SOM',
    icon: Wrench,
    time: 45,
    questions: 40,
    difficulty: 'Hard',
    color: 'from-rose-500/20 to-pink-500/20',
    iconColor: 'text-rose-400'
  },
  {
    id: 'full-mock',
    title: 'Full Placement Mock',
    description: 'Aptitude + Technical Combined',
    icon: GraduationCap,
    time: 60,
    questions: 60,
    difficulty: 'Advanced',
    color: 'from-purple-500/20 to-indigo-500/20',
    iconColor: 'text-purple-400'
  }
];

export default function PracticeTests() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [loadingId, setLoadingId] = useState<string | null>(null);

  const startTest = async (testId: string, testTitle: string, numQuestions: number, timeLimit: number) => {
    if (!user) return;
    
    setLoadingId(testId);
    try {
      const { data, error } = await supabase.functions.invoke('generate-test', {
        body: {
          test_type: testTitle,
          branch: testId.includes('cse') ? 'CSE' : testId.includes('ece') ? 'ECE' : testId.includes('me') ? 'ME' : 'General',
          num_questions: numQuestions
        }
      });

      if (error) throw error;
      if (!data?.success || !data?.questions) {
        throw new Error('Failed to generate test questions');
      }

      // Navigate to the test room with state
      navigate('/practice-tests/room', {
        state: {
          questions: data.questions,
          testType: testTitle,
          testId: testId,
          timeLimit: timeLimit * 60 // seconds
        }
      });

    } catch (error: any) {
      console.error("Test generation error:", error);
      toast.error(error.message || "Failed to generate test. Please try again.");
    } finally {
      setLoadingId(null);
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground pb-20">
      <Header />
      
      <main className="container max-w-7xl mx-auto px-4 pt-32">
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-display font-bold text-white mb-4">
            AI Practice Tests
          </h1>
          <p className="text-lg text-zinc-400 max-w-2xl">
            Hyper-personalized placement mocks generated by AI. 
            Questions adapt to your past performance to ensure you never solve the same problem twice.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {TEST_TYPES.map((test) => (
            <Card key={test.id} className="bg-zinc-900/50 border-zinc-800 backdrop-blur-sm overflow-hidden flex flex-col group transition-all duration-300 hover:border-zinc-700 hover:shadow-2xl hover:-translate-y-1">
              <div className={`h-2 w-full bg-gradient-to-r ${test.color}`} />
              
              <CardHeader>
                <div className="flex justify-between items-start mb-4">
                  <div className={`p-3 rounded-xl bg-black/40 ${test.iconColor}`}>
                    <test.icon className="w-6 h-6" />
                  </div>
                  <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-zinc-800/50 text-xs font-medium text-zinc-300 border border-zinc-700/50">
                    <AlertCircle className="w-3.5 h-3.5" />
                    {test.difficulty}
                  </div>
                </div>
                <CardTitle className="text-xl text-white font-bold">{test.title}</CardTitle>
                <CardDescription className="text-zinc-400 h-10">
                  {test.description}
                </CardDescription>
              </CardHeader>
              
              <CardContent className="flex-1">
                <div className="flex gap-4">
                  <div className="flex items-center gap-2 text-sm text-zinc-300">
                    <Clock className="w-4 h-4 text-zinc-500" />
                    {test.time} mins
                  </div>
                  <div className="flex items-center gap-2 text-sm text-zinc-300">
                    <HelpCircle className="w-4 h-4 text-zinc-500" />
                    {test.questions} Qs
                  </div>
                </div>
              </CardContent>

              <CardFooter>
                <Button 
                  className="w-full bg-white text-black hover:bg-zinc-200 transition-all font-semibold"
                  onClick={() => startTest(test.id, test.title, test.questions, test.time)}
                  disabled={loadingId !== null}
                >
                  {loadingId === test.id ? (
                    <div className="flex items-center gap-2">
                      <div className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin" />
                      Generating AI Test...
                    </div>
                  ) : (
                    'Start Test'
                  )}
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      </main>
    </div>
  );
}
