// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqdioubnjfqzvpsxcyxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZGlvdWJuamZxenZwc3hjeXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODA3MzYsImV4cCI6MjA3MTI1NjczNn0.bPns98QH0zRu3hD7tZr9CZ-4YFMJX8vnSihyExxSCeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});